version: '3.1'

services:
  web:
    build: .
    image: tocando-tierra:0.0.1
    restart: always
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: my-secret-pw
      WORDPRESS_DB_NAME: tocando_tierra
    volumes:
      - .\\template:/var/www/html/wp-content/themes/tocando-tierra
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db:/var/lib/mysql

volumes:
  db: